apiVersion: v1
kind: Service
metadata:
  name: gitops-by-argocd-service
spec:
  selector:
    app: gitops-by-argocd-app
  ports:
    - protocol: TCP
      port: 8686
      targetPort: 8686
  type: NodePort