apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-by-argocd-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bahram-jahanshahi/gitops-by-argocd.git
    targetRevision: HEAD
    path: k8s/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-by-argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

